"""fist migration: add QueryTemplate model

Revision ID: 2e1843d4af07
Revises: 
Create Date: 2021-08-04 10:51:34.627322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1843d4af07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_language', sa.String(length=120), nullable=False),
    sa.Column('query_text', sa.String(length=120), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_template')
    # ### end Alembic commands ###
