"""add url to QueryTemplate

Revision ID: 2999116f51e0
Revises: fa2fec14d21b
Create Date: 2021-10-04 17:56:45.119220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2999116f51e0'
down_revision = 'fa2fec14d21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_template', sa.Column('url', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_template', 'url')
    # ### end Alembic commands ###
