"""first migration

Revision ID: 37e9e7531e22
Revises: 
Create Date: 2021-08-16 07:04:59.701489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e9e7531e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_language', sa.String(length=120), nullable=False),
    sa.Column('query_text', sa.String(length=120), nullable=False),
    sa.Column('user', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_template')
    # ### end Alembic commands ###
