"""empty message

Revision ID: 3b687eb628d5
Revises: 266a37cb6dce
Create Date: 2022-07-01 15:27:33.487042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b687eb628d5'
down_revision = '266a37cb6dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_template', sa.Column('index', sa.String(length=120), nullable=True))
    op.drop_column('query_template', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_template', sa.Column('user', sa.VARCHAR(length=120), nullable=False))
    op.drop_column('query_template', 'index')
    # ### end Alembic commands ###
