"""first migration: QueryTemplate

Revision ID: 4919e8cec619
Revises: 
Create Date: 2021-06-29 19:41:18.209220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4919e8cec619'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('model_language', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_language'),
    sa.UniqueConstraint('model_name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_template')
    # ### end Alembic commands ###
