"""add text, code, equation and mode to QueryTemplate

Revision ID: fa2fec14d21b
Revises: 
Create Date: 2021-10-04 17:54:39.032404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa2fec14d21b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("mode", sa.String(length=80), nullable=False),
        sa.Column("language", sa.String(length=120), nullable=False),
        sa.Column("text", sa.String(length=120), nullable=True),
        sa.Column("code", sa.String(length=120), nullable=True),
        sa.Column("equation", sa.String(length=120), nullable=True),
        sa.Column("user", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_template")
    # ### end Alembic commands ###
